spring.application.name=loja
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lojajk
spring.datasource.username=postgres
spring.datasource.password=ifpb
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostrar SQL no console
spring.jpa.show-sql=true

# Formatar as SQLs no console
spring.jpa.properties.hibernate.format_sql=true

# Atualizar o banco automaticamente
spring.jpa.hibernate.ddl-auto=update